services:

  postgres:
    image: postgres:15
    container_name: insurance_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: insurance_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 5s
      retries: 5


  airflow-init:
    image: apache/airflow:2.9.3
    container_name: airflow_init
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      AIRFLOW_HOME: /opt/airflow
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__CORE__LOAD_EXAMPLES: "False"
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://postgres:postgres@insurance_postgres:5432/insurance_db
      _PIP_ADDITIONAL_REQUIREMENTS: pandas sqlalchemy psycopg2-binary
    volumes:
      - ./dags:/opt/airflow/dags
      - ./scripts:/opt/airflow/scripts
      - ./sql:/opt/airflow/sql
      - ./data:/opt/airflow/data
      - airflow_data:/opt/airflow
    command: >
      bash -c "
      airflow db migrate &&
      airflow users create
      --username admin
      --password admin
      --firstname admin
      --lastname user
      --role Admin
      --email admin@example.com || true
      "
    restart: on-failure


  airflow-webserver:
    image: apache/airflow:2.9.3
    container_name: airflow_webserver
    restart: always
    depends_on:
      postgres:
        condition: service_healthy
      airflow-init:
        condition: service_completed_successfully
    environment:
      AIRFLOW_HOME: /opt/airflow
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__CORE__LOAD_EXAMPLES: "False"
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://postgres:postgres@insurance_postgres:5432/insurance_db
      _PIP_ADDITIONAL_REQUIREMENTS: pandas sqlalchemy psycopg2-binary
    ports:
      - "8080:8080"
    volumes:
      - ./dags:/opt/airflow/dags
      - ./scripts:/opt/airflow/scripts
      - ./sql:/opt/airflow/sql
      - ./data:/opt/airflow/data
      - airflow_data:/opt/airflow
    command: airflow webserver


  airflow-scheduler:
    image: apache/airflow:2.9.3
    container_name: airflow_scheduler
    restart: always
    depends_on:
      postgres:
        condition: service_healthy
      airflow-init:
        condition: service_completed_successfully
    environment:
      AIRFLOW_HOME: /opt/airflow
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__CORE__LOAD_EXAMPLES: "False"
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://postgres:postgres@insurance_postgres:5432/insurance_db
      _PIP_ADDITIONAL_REQUIREMENTS: pandas sqlalchemy psycopg2-binary
    volumes:
      - ./dags:/opt/airflow/dags
      - ./scripts:/opt/airflow/scripts
      - ./sql:/opt/airflow/sql
      - ./data:/opt/airflow/data
      - airflow_data:/opt/airflow
    command: airflow scheduler


  metabase:
    image: metabase/metabase:latest
    container_name: insurance_metabase
    restart: always
    ports:
      - "3000:3000"


volumes:
  postgres_data:
  airflow_data: