insurance_dbt:
  target: dev
  outputs:
    dev:
      type: bigquery
      method: service-account
      project: "{{ env_var('GCP_PROJECT', 'insurance-data-platform-493115') }}"
      dataset: raw
      keyfile: "{{ env_var('GOOGLE_APPLICATION_CREDENTIALS', '') }}"
      location: asia-southeast1
      threads: 4
